baseURL = "http://example.org/"
languageCode = "en-us"
title = "Ariella Cheskis-Gold"

# enable Google Analytics
googleAnalytics = ""

# style options: default (pink), blue, green, pink, red, sea, violet
# use custom.css for your custom styling
style = "default"
description = "Portfolio of the amazing Ariella Cheskis-Gold"
copyright = "&copy;2017 Ariella Cheskis-Gold"
sidebarAbout = [
"I am a Associate Tech Director with more than 5 years of experience.",
"From CT, based in NYC, and dreaming of Prague."
]


  # Contact page
     # Since this template is static, the contact form uses www.formspree.io as a
     # proxy. The form makes a POST request to their servers to send the actual
     # email. Visitors can send up to a 1000 emails each month for free.
     #
     # What you need to do for the setup?
     #
     # - set your email address under 'email' below
     # - upload the generated site to your server
     # - send a dummy email yourself to confirm your account
     # - click the confirm link in the email from www.formspree.io
     # - you're done. Happy mailing!
  email = "you@yoursite.com"

  # Nav links in the side bar
  [[params.navlinks]]
  name = "Home"
  url = ""

  [[params.navlinks]]
  name = "About"
  url = "about/"

  [[params.navlinks]]
  name = "Get in touch"
  url = "contact/"

  [params.social]
  facebook      = "full page or profile url in facebook"
  googleplus    = "full profile url in googleplus"
  email         = "acheskisgold@gmail.com"
  twitter       = "full profile url in twitter"
  linkedin      = "https://www.linkedin.com/in/ariellacheskisgold/"
  stackoverflow = "full profile url in stackoverflow"
  instagram     = "full profile url in instagram"
  github        = "https://github.com/ariellacg"
